version: '3'

services:

  server:
    container_name: faceto-ai-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Server
    ports:
        - "8001:8001"
        - "9001:9001"

  web:
    container_name: faceto-ai-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Web
    ports:
      - "3000:3000"