// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// AuthToken is the predicate function for authtoken builders.
type AuthToken func(*sql.Selector)

// Link is the predicate function for link builders.
type Link func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// RoomMessage is the predicate function for roommessage builders.
type RoomMessage func(*sql.Selector)

// RoomVod is the predicate function for roomvod builders.
type RoomVod func(*sql.Selector)

// RoomWebhook is the predicate function for roomwebhook builders.
type RoomWebhook func(*sql.Selector)

// ServiceWebhookLog is the predicate function for servicewebhooklog builders.
type ServiceWebhookLog func(*sql.Selector)
