// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: room/v1/room.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NilReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NilReply) Reset() {
	*x = NilReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NilReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NilReply) ProtoMessage() {}

func (x *NilReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NilReply.ProtoReflect.Descriptor instead.
func (*NilReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

type HealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinRoomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sid  string `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *JoinRoomReply) Reset() {
	*x = JoinRoomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReply) ProtoMessage() {}

func (x *JoinRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReply.ProtoReflect.Descriptor instead.
func (*JoinRoomReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRoomReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinRoomReply) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type WebhookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WebhookRequest) Reset() {
	*x = WebhookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookRequest) ProtoMessage() {}

func (x *WebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookRequest.ProtoReflect.Descriptor instead.
func (*WebhookRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{5}
}

type CheckRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	C    string `protobuf:"bytes,2,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *CheckRoomRequest) Reset() {
	*x = CheckRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomRequest) ProtoMessage() {}

func (x *CheckRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomRequest.ProtoReflect.Descriptor instead.
func (*CheckRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *CheckRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckRoomRequest) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

type CheckRoomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *CheckRoomReply) Reset() {
	*x = CheckRoomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomReply) ProtoMessage() {}

func (x *CheckRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomReply.ProtoReflect.Descriptor instead.
func (*CheckRoomReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *CheckRoomReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type RoomTranscriptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *RoomTranscriptRequest) Reset() {
	*x = RoomTranscriptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomTranscriptRequest) ProtoMessage() {}

func (x *RoomTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomTranscriptRequest.ProtoReflect.Descriptor instead.
func (*RoomTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *RoomTranscriptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomTranscriptRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type RoomTranscriptReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// version
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// room info
	Room *RoomTranscriptReply_Room `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	// room transcript list
	Transcript *RoomTranscriptReply_Transcript `protobuf:"bytes,3,opt,name=transcript,proto3" json:"transcript,omitempty"`
	Vod        *RoomTranscriptReply_Vod        `protobuf:"bytes,4,opt,name=vod,proto3" json:"vod,omitempty"`
}

func (x *RoomTranscriptReply) Reset() {
	*x = RoomTranscriptReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomTranscriptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomTranscriptReply) ProtoMessage() {}

func (x *RoomTranscriptReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomTranscriptReply.ProtoReflect.Descriptor instead.
func (*RoomTranscriptReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *RoomTranscriptReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RoomTranscriptReply) GetRoom() *RoomTranscriptReply_Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RoomTranscriptReply) GetTranscript() *RoomTranscriptReply_Transcript {
	if x != nil {
		return x.Transcript
	}
	return nil
}

func (x *RoomTranscriptReply) GetVod() *RoomTranscriptReply_Vod {
	if x != nil {
		return x.Vod
	}
	return nil
}

type SetRoomVoiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName string `protobuf:"bytes,1,opt,name=room_name,proto3" json:"room_name,omitempty"`
	VoiceId  string `protobuf:"bytes,2,opt,name=voice_id,proto3" json:"voice_id,omitempty"`
}

func (x *SetRoomVoiceRequest) Reset() {
	*x = SetRoomVoiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRoomVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomVoiceRequest) ProtoMessage() {}

func (x *SetRoomVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomVoiceRequest.ProtoReflect.Descriptor instead.
func (*SetRoomVoiceRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *SetRoomVoiceRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *SetRoomVoiceRequest) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

type RoomTranscriptReply_Transcript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*RoomTranscriptReply_Transcript_List `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RoomTranscriptReply_Transcript) Reset() {
	*x = RoomTranscriptReply_Transcript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomTranscriptReply_Transcript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomTranscriptReply_Transcript) ProtoMessage() {}

func (x *RoomTranscriptReply_Transcript) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomTranscriptReply_Transcript.ProtoReflect.Descriptor instead.
func (*RoomTranscriptReply_Transcript) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{9, 0}
}

func (x *RoomTranscriptReply_Transcript) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RoomTranscriptReply_Transcript) GetList() []*RoomTranscriptReply_Transcript_List {
	if x != nil {
		return x.List
	}
	return nil
}

type RoomTranscriptReply_Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sid  string `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *RoomTranscriptReply_Room) Reset() {
	*x = RoomTranscriptReply_Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomTranscriptReply_Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomTranscriptReply_Room) ProtoMessage() {}

func (x *RoomTranscriptReply_Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomTranscriptReply_Room.ProtoReflect.Descriptor instead.
func (*RoomTranscriptReply_Room) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{9, 1}
}

func (x *RoomTranscriptReply_Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomTranscriptReply_Room) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type RoomTranscriptReply_Vod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EgressId     string `protobuf:"bytes,1,opt,name=egress_id,proto3" json:"egress_id,omitempty"`
	Url          string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Status       uint32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	StartTime    uint32 `protobuf:"varint,4,opt,name=start_time,proto3" json:"start_time,omitempty"`
	CompleteTime uint32 `protobuf:"varint,5,opt,name=complete_time,proto3" json:"complete_time,omitempty"`
	Duration     uint32 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *RoomTranscriptReply_Vod) Reset() {
	*x = RoomTranscriptReply_Vod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomTranscriptReply_Vod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomTranscriptReply_Vod) ProtoMessage() {}

func (x *RoomTranscriptReply_Vod) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomTranscriptReply_Vod.ProtoReflect.Descriptor instead.
func (*RoomTranscriptReply_Vod) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{9, 2}
}

func (x *RoomTranscriptReply_Vod) GetEgressId() string {
	if x != nil {
		return x.EgressId
	}
	return ""
}

func (x *RoomTranscriptReply_Vod) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RoomTranscriptReply_Vod) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoomTranscriptReply_Vod) GetStartTime() uint32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *RoomTranscriptReply_Vod) GetCompleteTime() uint32 {
	if x != nil {
		return x.CompleteTime
	}
	return 0
}

func (x *RoomTranscriptReply_Vod) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type RoomTranscriptReply_Transcript_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsBot bool `protobuf:"varint,1,opt,name=is_bot,proto3" json:"is_bot,omitempty"`
	// current name of this talk
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text      string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *RoomTranscriptReply_Transcript_List) Reset() {
	*x = RoomTranscriptReply_Transcript_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_v1_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomTranscriptReply_Transcript_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomTranscriptReply_Transcript_List) ProtoMessage() {}

func (x *RoomTranscriptReply_Transcript_List) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomTranscriptReply_Transcript_List.ProtoReflect.Descriptor instead.
func (*RoomTranscriptReply_Transcript_List) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{9, 0, 0}
}

func (x *RoomTranscriptReply_Transcript_List) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *RoomTranscriptReply_Transcript_List) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomTranscriptReply_Transcript_List) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RoomTranscriptReply_Transcript_List) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_room_v1_room_proto protoreflect.FileDescriptor

var file_room_v1_room_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e,
	0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x26, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x4e, 0x69, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x0d,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x73, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0c, 0x0a,
	0x01, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x63, 0x22, 0x26, 0x0a, 0x0e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x15, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x22, 0xa4, 0x05, 0x0a, 0x13, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f,
	0x6f, 0x6d, 0x12, 0x4c, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69,
	0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x12, 0x37, 0x0a, 0x03, 0x76, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x56, 0x6f, 0x64, 0x52, 0x03, 0x76, 0x6f, 0x64, 0x1a, 0xcf, 0x01, 0x0a, 0x0a, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x45,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x64, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x73, 0x5f, 0x62, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x5f, 0x62, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x1a, 0x2c, 0x0a, 0x04, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x1a, 0xaf, 0x01, 0x0a, 0x03, 0x56, 0x6f,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x13, 0x53,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x32, 0xfb, 0x04, 0x0a,
	0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x4a, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12,
	0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x09, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x03, 0x12, 0x01,
	0x2f, 0x12, 0x63, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1e,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x12, 0x3a, 0x01, 0x2a, 0x22, 0x0d, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f,
	0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x5f, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x1d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76,
	0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x22, 0x0c, 0x2f, 0x6a, 0x6f, 0x69, 0x6e,
	0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x7d, 0x0a, 0x14, 0x52, 0x6f, 0x6f, 0x6d, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x23, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a,
	0x01, 0x2a, 0x22, 0x12, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x78, 0x0a, 0x0e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x23, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01, 0x2a, 0x22, 0x13, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x12, 0x68, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x6f, 0x69, 0x63, 0x65,
	0x12, 0x21, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e,
	0x76, 0x31, 0x2e, 0x4e, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x22, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6f, 0x6d,
	0x2f, 0x73, 0x65, 0x74, 0x5f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x42, 0x41, 0x0a, 0x16, 0x64, 0x65,
	0x76, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56,
	0x31, 0x50, 0x01, 0x5a, 0x18, 0x66, 0x61, 0x63, 0x65, 0x74, 0x6f, 0x2d, 0x61, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData = file_room_v1_room_proto_rawDesc
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_v1_room_proto_rawDescData)
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_room_v1_room_proto_goTypes = []interface{}{
	(*HelloReply)(nil),                          // 0: interview.v1.HelloReply
	(*NilReply)(nil),                            // 1: interview.v1.NilReply
	(*HealthRequest)(nil),                       // 2: interview.v1.HealthRequest
	(*JoinRoomRequest)(nil),                     // 3: interview.v1.JoinRoomRequest
	(*JoinRoomReply)(nil),                       // 4: interview.v1.JoinRoomReply
	(*WebhookRequest)(nil),                      // 5: interview.v1.WebhookRequest
	(*CheckRoomRequest)(nil),                    // 6: interview.v1.CheckRoomRequest
	(*CheckRoomReply)(nil),                      // 7: interview.v1.CheckRoomReply
	(*RoomTranscriptRequest)(nil),               // 8: interview.v1.RoomTranscriptRequest
	(*RoomTranscriptReply)(nil),                 // 9: interview.v1.RoomTranscriptReply
	(*SetRoomVoiceRequest)(nil),                 // 10: interview.v1.SetRoomVoiceRequest
	(*RoomTranscriptReply_Transcript)(nil),      // 11: interview.v1.RoomTranscriptReply.Transcript
	(*RoomTranscriptReply_Room)(nil),            // 12: interview.v1.RoomTranscriptReply.Room
	(*RoomTranscriptReply_Vod)(nil),             // 13: interview.v1.RoomTranscriptReply.Vod
	(*RoomTranscriptReply_Transcript_List)(nil), // 14: interview.v1.RoomTranscriptReply.Transcript.List
}
var file_room_v1_room_proto_depIdxs = []int32{
	12, // 0: interview.v1.RoomTranscriptReply.room:type_name -> interview.v1.RoomTranscriptReply.Room
	11, // 1: interview.v1.RoomTranscriptReply.transcript:type_name -> interview.v1.RoomTranscriptReply.Transcript
	13, // 2: interview.v1.RoomTranscriptReply.vod:type_name -> interview.v1.RoomTranscriptReply.Vod
	14, // 3: interview.v1.RoomTranscriptReply.Transcript.list:type_name -> interview.v1.RoomTranscriptReply.Transcript.List
	2,  // 4: interview.v1.Room.Health:input_type -> interview.v1.HealthRequest
	6,  // 5: interview.v1.Room.CheckRoom:input_type -> interview.v1.CheckRoomRequest
	3,  // 6: interview.v1.Room.JoinRoom:input_type -> interview.v1.JoinRoomRequest
	8,  // 7: interview.v1.Room.RoomTranscriptOnline:input_type -> interview.v1.RoomTranscriptRequest
	8,  // 8: interview.v1.Room.RoomTranscript:input_type -> interview.v1.RoomTranscriptRequest
	10, // 9: interview.v1.Room.SetRoomVoice:input_type -> interview.v1.SetRoomVoiceRequest
	0,  // 10: interview.v1.Room.Health:output_type -> interview.v1.HelloReply
	7,  // 11: interview.v1.Room.CheckRoom:output_type -> interview.v1.CheckRoomReply
	4,  // 12: interview.v1.Room.JoinRoom:output_type -> interview.v1.JoinRoomReply
	9,  // 13: interview.v1.Room.RoomTranscriptOnline:output_type -> interview.v1.RoomTranscriptReply
	9,  // 14: interview.v1.Room.RoomTranscript:output_type -> interview.v1.RoomTranscriptReply
	1,  // 15: interview.v1.Room.SetRoomVoice:output_type -> interview.v1.NilReply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_v1_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NilReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRoomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomTranscriptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomTranscriptReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRoomVoiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomTranscriptReply_Transcript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomTranscriptReply_Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomTranscriptReply_Vod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_v1_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomTranscriptReply_Transcript_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_v1_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_rawDesc = nil
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
