// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"faceto-ai/internal/data/ent/auth"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthCreate is the builder for creating a Auth entity.
type AuthCreate struct {
	config
	mutation *AuthMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (ac *AuthCreate) SetUUID(s string) *AuthCreate {
	ac.mutation.SetUUID(s)
	return ac
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (ac *AuthCreate) SetNillableUUID(s *string) *AuthCreate {
	if s != nil {
		ac.SetUUID(*s)
	}
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AuthCreate) SetCreatedAt(t time.Time) *AuthCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AuthCreate) SetNillableCreatedAt(t *time.Time) *AuthCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AuthCreate) SetUpdatedAt(t time.Time) *AuthCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AuthCreate) SetNillableUpdatedAt(t *time.Time) *AuthCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetDeletedAt sets the "deleted_at" field.
func (ac *AuthCreate) SetDeletedAt(t time.Time) *AuthCreate {
	ac.mutation.SetDeletedAt(t)
	return ac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ac *AuthCreate) SetNillableDeletedAt(t *time.Time) *AuthCreate {
	if t != nil {
		ac.SetDeletedAt(*t)
	}
	return ac
}

// SetClientID sets the "client_id" field.
func (ac *AuthCreate) SetClientID(s string) *AuthCreate {
	ac.mutation.SetClientID(s)
	return ac
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (ac *AuthCreate) SetNillableClientID(s *string) *AuthCreate {
	if s != nil {
		ac.SetClientID(*s)
	}
	return ac
}

// SetClientSecret sets the "client_secret" field.
func (ac *AuthCreate) SetClientSecret(s string) *AuthCreate {
	ac.mutation.SetClientSecret(s)
	return ac
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (ac *AuthCreate) SetNillableClientSecret(s *string) *AuthCreate {
	if s != nil {
		ac.SetClientSecret(*s)
	}
	return ac
}

// SetGrantScope sets the "grant_scope" field.
func (ac *AuthCreate) SetGrantScope(s string) *AuthCreate {
	ac.mutation.SetGrantScope(s)
	return ac
}

// SetNillableGrantScope sets the "grant_scope" field if the given value is not nil.
func (ac *AuthCreate) SetNillableGrantScope(s *string) *AuthCreate {
	if s != nil {
		ac.SetGrantScope(*s)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AuthCreate) SetID(u uint64) *AuthCreate {
	ac.mutation.SetID(u)
	return ac
}

// Mutation returns the AuthMutation object of the builder.
func (ac *AuthCreate) Mutation() *AuthMutation {
	return ac.mutation
}

// Save creates the Auth in the database.
func (ac *AuthCreate) Save(ctx context.Context) (*Auth, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AuthCreate) SaveX(ctx context.Context) *Auth {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AuthCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AuthCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AuthCreate) defaults() {
	if _, ok := ac.mutation.UUID(); !ok {
		v := auth.DefaultUUID()
		ac.mutation.SetUUID(v)
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := auth.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		v := auth.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
	if _, ok := ac.mutation.ClientID(); !ok {
		v := auth.DefaultClientID
		ac.mutation.SetClientID(v)
	}
	if _, ok := ac.mutation.ClientSecret(); !ok {
		v := auth.DefaultClientSecret
		ac.mutation.SetClientSecret(v)
	}
	if _, ok := ac.mutation.GrantScope(); !ok {
		v := auth.DefaultGrantScope
		ac.mutation.SetGrantScope(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AuthCreate) check() error {
	if _, ok := ac.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "Auth.uuid"`)}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Auth.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Auth.updated_at"`)}
	}
	if _, ok := ac.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "Auth.client_id"`)}
	}
	return nil
}

func (ac *AuthCreate) sqlSave(ctx context.Context) (*Auth, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AuthCreate) createSpec() (*Auth, *sqlgraph.CreateSpec) {
	var (
		_node = &Auth{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(auth.Table, sqlgraph.NewFieldSpec(auth.FieldID, field.TypeUint64))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.UUID(); ok {
		_spec.SetField(auth.FieldUUID, field.TypeString, value)
		_node.UUID = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(auth.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(auth.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ac.mutation.DeletedAt(); ok {
		_spec.SetField(auth.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := ac.mutation.ClientID(); ok {
		_spec.SetField(auth.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := ac.mutation.ClientSecret(); ok {
		_spec.SetField(auth.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	if value, ok := ac.mutation.GrantScope(); ok {
		_spec.SetField(auth.FieldGrantScope, field.TypeString, value)
		_node.GrantScope = value
	}
	return _node, _spec
}

// AuthCreateBulk is the builder for creating many Auth entities in bulk.
type AuthCreateBulk struct {
	config
	builders []*AuthCreate
}

// Save creates the Auth entities in the database.
func (acb *AuthCreateBulk) Save(ctx context.Context) ([]*Auth, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Auth, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AuthCreateBulk) SaveX(ctx context.Context) []*Auth {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AuthCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AuthCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
