// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"faceto-ai/internal/data/ent/authtoken"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthTokenCreate is the builder for creating a AuthToken entity.
type AuthTokenCreate struct {
	config
	mutation *AuthTokenMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (atc *AuthTokenCreate) SetUUID(s string) *AuthTokenCreate {
	atc.mutation.SetUUID(s)
	return atc
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (atc *AuthTokenCreate) SetNillableUUID(s *string) *AuthTokenCreate {
	if s != nil {
		atc.SetUUID(*s)
	}
	return atc
}

// SetCreatedAt sets the "created_at" field.
func (atc *AuthTokenCreate) SetCreatedAt(t time.Time) *AuthTokenCreate {
	atc.mutation.SetCreatedAt(t)
	return atc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (atc *AuthTokenCreate) SetNillableCreatedAt(t *time.Time) *AuthTokenCreate {
	if t != nil {
		atc.SetCreatedAt(*t)
	}
	return atc
}

// SetUpdatedAt sets the "updated_at" field.
func (atc *AuthTokenCreate) SetUpdatedAt(t time.Time) *AuthTokenCreate {
	atc.mutation.SetUpdatedAt(t)
	return atc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (atc *AuthTokenCreate) SetNillableUpdatedAt(t *time.Time) *AuthTokenCreate {
	if t != nil {
		atc.SetUpdatedAt(*t)
	}
	return atc
}

// SetDeletedAt sets the "deleted_at" field.
func (atc *AuthTokenCreate) SetDeletedAt(t time.Time) *AuthTokenCreate {
	atc.mutation.SetDeletedAt(t)
	return atc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (atc *AuthTokenCreate) SetNillableDeletedAt(t *time.Time) *AuthTokenCreate {
	if t != nil {
		atc.SetDeletedAt(*t)
	}
	return atc
}

// SetClientID sets the "client_id" field.
func (atc *AuthTokenCreate) SetClientID(s string) *AuthTokenCreate {
	atc.mutation.SetClientID(s)
	return atc
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (atc *AuthTokenCreate) SetNillableClientID(s *string) *AuthTokenCreate {
	if s != nil {
		atc.SetClientID(*s)
	}
	return atc
}

// SetAccessToken sets the "access_token" field.
func (atc *AuthTokenCreate) SetAccessToken(s string) *AuthTokenCreate {
	atc.mutation.SetAccessToken(s)
	return atc
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (atc *AuthTokenCreate) SetNillableAccessToken(s *string) *AuthTokenCreate {
	if s != nil {
		atc.SetAccessToken(*s)
	}
	return atc
}

// SetRefreshToken sets the "refresh_token" field.
func (atc *AuthTokenCreate) SetRefreshToken(s string) *AuthTokenCreate {
	atc.mutation.SetRefreshToken(s)
	return atc
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (atc *AuthTokenCreate) SetNillableRefreshToken(s *string) *AuthTokenCreate {
	if s != nil {
		atc.SetRefreshToken(*s)
	}
	return atc
}

// SetExpiresIn sets the "expires_in" field.
func (atc *AuthTokenCreate) SetExpiresIn(t time.Time) *AuthTokenCreate {
	atc.mutation.SetExpiresIn(t)
	return atc
}

// SetNillableExpiresIn sets the "expires_in" field if the given value is not nil.
func (atc *AuthTokenCreate) SetNillableExpiresIn(t *time.Time) *AuthTokenCreate {
	if t != nil {
		atc.SetExpiresIn(*t)
	}
	return atc
}

// SetID sets the "id" field.
func (atc *AuthTokenCreate) SetID(u uint64) *AuthTokenCreate {
	atc.mutation.SetID(u)
	return atc
}

// Mutation returns the AuthTokenMutation object of the builder.
func (atc *AuthTokenCreate) Mutation() *AuthTokenMutation {
	return atc.mutation
}

// Save creates the AuthToken in the database.
func (atc *AuthTokenCreate) Save(ctx context.Context) (*AuthToken, error) {
	atc.defaults()
	return withHooks(ctx, atc.sqlSave, atc.mutation, atc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (atc *AuthTokenCreate) SaveX(ctx context.Context) *AuthToken {
	v, err := atc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atc *AuthTokenCreate) Exec(ctx context.Context) error {
	_, err := atc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atc *AuthTokenCreate) ExecX(ctx context.Context) {
	if err := atc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (atc *AuthTokenCreate) defaults() {
	if _, ok := atc.mutation.UUID(); !ok {
		v := authtoken.DefaultUUID()
		atc.mutation.SetUUID(v)
	}
	if _, ok := atc.mutation.CreatedAt(); !ok {
		v := authtoken.DefaultCreatedAt()
		atc.mutation.SetCreatedAt(v)
	}
	if _, ok := atc.mutation.UpdatedAt(); !ok {
		v := authtoken.DefaultUpdatedAt()
		atc.mutation.SetUpdatedAt(v)
	}
	if _, ok := atc.mutation.ClientID(); !ok {
		v := authtoken.DefaultClientID
		atc.mutation.SetClientID(v)
	}
	if _, ok := atc.mutation.AccessToken(); !ok {
		v := authtoken.DefaultAccessToken
		atc.mutation.SetAccessToken(v)
	}
	if _, ok := atc.mutation.RefreshToken(); !ok {
		v := authtoken.DefaultRefreshToken
		atc.mutation.SetRefreshToken(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atc *AuthTokenCreate) check() error {
	if _, ok := atc.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "AuthToken.uuid"`)}
	}
	if _, ok := atc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthToken.created_at"`)}
	}
	if _, ok := atc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthToken.updated_at"`)}
	}
	if _, ok := atc.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "AuthToken.client_id"`)}
	}
	return nil
}

func (atc *AuthTokenCreate) sqlSave(ctx context.Context) (*AuthToken, error) {
	if err := atc.check(); err != nil {
		return nil, err
	}
	_node, _spec := atc.createSpec()
	if err := sqlgraph.CreateNode(ctx, atc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	atc.mutation.id = &_node.ID
	atc.mutation.done = true
	return _node, nil
}

func (atc *AuthTokenCreate) createSpec() (*AuthToken, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthToken{config: atc.config}
		_spec = sqlgraph.NewCreateSpec(authtoken.Table, sqlgraph.NewFieldSpec(authtoken.FieldID, field.TypeUint64))
	)
	if id, ok := atc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := atc.mutation.UUID(); ok {
		_spec.SetField(authtoken.FieldUUID, field.TypeString, value)
		_node.UUID = value
	}
	if value, ok := atc.mutation.CreatedAt(); ok {
		_spec.SetField(authtoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := atc.mutation.UpdatedAt(); ok {
		_spec.SetField(authtoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := atc.mutation.DeletedAt(); ok {
		_spec.SetField(authtoken.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := atc.mutation.ClientID(); ok {
		_spec.SetField(authtoken.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := atc.mutation.AccessToken(); ok {
		_spec.SetField(authtoken.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := atc.mutation.RefreshToken(); ok {
		_spec.SetField(authtoken.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := atc.mutation.ExpiresIn(); ok {
		_spec.SetField(authtoken.FieldExpiresIn, field.TypeTime, value)
		_node.ExpiresIn = value
	}
	return _node, _spec
}

// AuthTokenCreateBulk is the builder for creating many AuthToken entities in bulk.
type AuthTokenCreateBulk struct {
	config
	builders []*AuthTokenCreate
}

// Save creates the AuthToken entities in the database.
func (atcb *AuthTokenCreateBulk) Save(ctx context.Context) ([]*AuthToken, error) {
	specs := make([]*sqlgraph.CreateSpec, len(atcb.builders))
	nodes := make([]*AuthToken, len(atcb.builders))
	mutators := make([]Mutator, len(atcb.builders))
	for i := range atcb.builders {
		func(i int, root context.Context) {
			builder := atcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, atcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, atcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, atcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (atcb *AuthTokenCreateBulk) SaveX(ctx context.Context) []*AuthToken {
	v, err := atcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atcb *AuthTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := atcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atcb *AuthTokenCreateBulk) ExecX(ctx context.Context) {
	if err := atcb.Exec(ctx); err != nil {
		panic(err)
	}
}
