// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"faceto-ai/internal/data/ent/predicate"
	"faceto-ai/internal/data/ent/roommessage"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoomMessageQuery is the builder for querying RoomMessage entities.
type RoomMessageQuery struct {
	config
	ctx        *QueryContext
	order      []roommessage.OrderOption
	inters     []Interceptor
	predicates []predicate.RoomMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoomMessageQuery builder.
func (rmq *RoomMessageQuery) Where(ps ...predicate.RoomMessage) *RoomMessageQuery {
	rmq.predicates = append(rmq.predicates, ps...)
	return rmq
}

// Limit the number of records to be returned by this query.
func (rmq *RoomMessageQuery) Limit(limit int) *RoomMessageQuery {
	rmq.ctx.Limit = &limit
	return rmq
}

// Offset to start from.
func (rmq *RoomMessageQuery) Offset(offset int) *RoomMessageQuery {
	rmq.ctx.Offset = &offset
	return rmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rmq *RoomMessageQuery) Unique(unique bool) *RoomMessageQuery {
	rmq.ctx.Unique = &unique
	return rmq
}

// Order specifies how the records should be ordered.
func (rmq *RoomMessageQuery) Order(o ...roommessage.OrderOption) *RoomMessageQuery {
	rmq.order = append(rmq.order, o...)
	return rmq
}

// First returns the first RoomMessage entity from the query.
// Returns a *NotFoundError when no RoomMessage was found.
func (rmq *RoomMessageQuery) First(ctx context.Context) (*RoomMessage, error) {
	nodes, err := rmq.Limit(1).All(setContextOp(ctx, rmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roommessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rmq *RoomMessageQuery) FirstX(ctx context.Context) *RoomMessage {
	node, err := rmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoomMessage ID from the query.
// Returns a *NotFoundError when no RoomMessage ID was found.
func (rmq *RoomMessageQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = rmq.Limit(1).IDs(setContextOp(ctx, rmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roommessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rmq *RoomMessageQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := rmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoomMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoomMessage entity is found.
// Returns a *NotFoundError when no RoomMessage entities are found.
func (rmq *RoomMessageQuery) Only(ctx context.Context) (*RoomMessage, error) {
	nodes, err := rmq.Limit(2).All(setContextOp(ctx, rmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roommessage.Label}
	default:
		return nil, &NotSingularError{roommessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rmq *RoomMessageQuery) OnlyX(ctx context.Context) *RoomMessage {
	node, err := rmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoomMessage ID in the query.
// Returns a *NotSingularError when more than one RoomMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (rmq *RoomMessageQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = rmq.Limit(2).IDs(setContextOp(ctx, rmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roommessage.Label}
	default:
		err = &NotSingularError{roommessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rmq *RoomMessageQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := rmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoomMessages.
func (rmq *RoomMessageQuery) All(ctx context.Context) ([]*RoomMessage, error) {
	ctx = setContextOp(ctx, rmq.ctx, "All")
	if err := rmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoomMessage, *RoomMessageQuery]()
	return withInterceptors[[]*RoomMessage](ctx, rmq, qr, rmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rmq *RoomMessageQuery) AllX(ctx context.Context) []*RoomMessage {
	nodes, err := rmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoomMessage IDs.
func (rmq *RoomMessageQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if rmq.ctx.Unique == nil && rmq.path != nil {
		rmq.Unique(true)
	}
	ctx = setContextOp(ctx, rmq.ctx, "IDs")
	if err = rmq.Select(roommessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rmq *RoomMessageQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := rmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rmq *RoomMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Count")
	if err := rmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rmq, querierCount[*RoomMessageQuery](), rmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rmq *RoomMessageQuery) CountX(ctx context.Context) int {
	count, err := rmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rmq *RoomMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Exist")
	switch _, err := rmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rmq *RoomMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := rmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoomMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rmq *RoomMessageQuery) Clone() *RoomMessageQuery {
	if rmq == nil {
		return nil
	}
	return &RoomMessageQuery{
		config:     rmq.config,
		ctx:        rmq.ctx.Clone(),
		order:      append([]roommessage.OrderOption{}, rmq.order...),
		inters:     append([]Interceptor{}, rmq.inters...),
		predicates: append([]predicate.RoomMessage{}, rmq.predicates...),
		// clone intermediate query.
		sql:  rmq.sql.Clone(),
		path: rmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoomMessage.Query().
//		GroupBy(roommessage.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rmq *RoomMessageQuery) GroupBy(field string, fields ...string) *RoomMessageGroupBy {
	rmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoomMessageGroupBy{build: rmq}
	grbuild.flds = &rmq.ctx.Fields
	grbuild.label = roommessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//	}
//
//	client.RoomMessage.Query().
//		Select(roommessage.FieldUUID).
//		Scan(ctx, &v)
func (rmq *RoomMessageQuery) Select(fields ...string) *RoomMessageSelect {
	rmq.ctx.Fields = append(rmq.ctx.Fields, fields...)
	sbuild := &RoomMessageSelect{RoomMessageQuery: rmq}
	sbuild.label = roommessage.Label
	sbuild.flds, sbuild.scan = &rmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoomMessageSelect configured with the given aggregations.
func (rmq *RoomMessageQuery) Aggregate(fns ...AggregateFunc) *RoomMessageSelect {
	return rmq.Select().Aggregate(fns...)
}

func (rmq *RoomMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rmq); err != nil {
				return err
			}
		}
	}
	for _, f := range rmq.ctx.Fields {
		if !roommessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rmq.path != nil {
		prev, err := rmq.path(ctx)
		if err != nil {
			return err
		}
		rmq.sql = prev
	}
	return nil
}

func (rmq *RoomMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoomMessage, error) {
	var (
		nodes = []*RoomMessage{}
		_spec = rmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoomMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoomMessage{config: rmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rmq *RoomMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rmq.querySpec()
	_spec.Node.Columns = rmq.ctx.Fields
	if len(rmq.ctx.Fields) > 0 {
		_spec.Unique = rmq.ctx.Unique != nil && *rmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rmq.driver, _spec)
}

func (rmq *RoomMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roommessage.Table, roommessage.Columns, sqlgraph.NewFieldSpec(roommessage.FieldID, field.TypeUint64))
	_spec.From = rmq.sql
	if unique := rmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rmq.path != nil {
		_spec.Unique = true
	}
	if fields := rmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roommessage.FieldID)
		for i := range fields {
			if fields[i] != roommessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rmq *RoomMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rmq.driver.Dialect())
	t1 := builder.Table(roommessage.Table)
	columns := rmq.ctx.Fields
	if len(columns) == 0 {
		columns = roommessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rmq.sql != nil {
		selector = rmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rmq.ctx.Unique != nil && *rmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rmq.predicates {
		p(selector)
	}
	for _, p := range rmq.order {
		p(selector)
	}
	if offset := rmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoomMessageGroupBy is the group-by builder for RoomMessage entities.
type RoomMessageGroupBy struct {
	selector
	build *RoomMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rmgb *RoomMessageGroupBy) Aggregate(fns ...AggregateFunc) *RoomMessageGroupBy {
	rmgb.fns = append(rmgb.fns, fns...)
	return rmgb
}

// Scan applies the selector query and scans the result into the given value.
func (rmgb *RoomMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmgb.build.ctx, "GroupBy")
	if err := rmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoomMessageQuery, *RoomMessageGroupBy](ctx, rmgb.build, rmgb, rmgb.build.inters, v)
}

func (rmgb *RoomMessageGroupBy) sqlScan(ctx context.Context, root *RoomMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rmgb.fns))
	for _, fn := range rmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rmgb.flds)+len(rmgb.fns))
		for _, f := range *rmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoomMessageSelect is the builder for selecting fields of RoomMessage entities.
type RoomMessageSelect struct {
	*RoomMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rms *RoomMessageSelect) Aggregate(fns ...AggregateFunc) *RoomMessageSelect {
	rms.fns = append(rms.fns, fns...)
	return rms
}

// Scan applies the selector query and scans the result into the given value.
func (rms *RoomMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rms.ctx, "Select")
	if err := rms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoomMessageQuery, *RoomMessageSelect](ctx, rms.RoomMessageQuery, rms, rms.inters, v)
}

func (rms *RoomMessageSelect) sqlScan(ctx context.Context, root *RoomMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rms.fns))
	for _, fn := range rms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
