// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Auth struct {
	ent.Schema
}

func (Auth) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id"),
		field.String("client_id").Default(""),
		field.String("client_secret").Default("").Optional(),
		field.String("grant_scope").Default("").Optional(),
	}
}

func (Auth) Edges() []ent.Edge {
	return []ent.Edge{}
}

func (Auth) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "auth"}}
}

func (Auth) Mixin() []ent.Mixin {
	return []ent.Mixin{
		UUIDMixin{},
		TimeMixin{},
	}
}
