// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type ServiceWebhookLog struct {
	ent.Schema
}

type WebhookRequest struct {
	Data interface{} `json:"data"`
}

type WebhookResp struct {
	Data interface{} `json:"data"`
}

func (ServiceWebhookLog) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id"),
		field.String("name").Default(""),
		field.String("sid").Default(""),
		field.String("url").Default(""),
		field.Uint16("status_code").Default(0).Optional(),
		field.Uint8("times").Default(0).Optional(),
		field.JSON("request", &WebhookRequest{}).Optional(),
		field.JSON("resp", &WebhookResp{}).Optional(),
	}
}

func (ServiceWebhookLog) Edges() []ent.Edge {
	return []ent.Edge{}
}

func (ServiceWebhookLog) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "service_webhook_log"}}
}

func (ServiceWebhookLog) Mixin() []ent.Mixin {
	return []ent.Mixin{
		UUIDMixin{},
		TimeMixin{},
	}
}
