// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthColumns holds the columns for the "auth" table.
	AuthColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "client_id", Type: field.TypeString, Default: ""},
		{Name: "client_secret", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "grant_scope", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// AuthTable holds the schema information for the "auth" table.
	AuthTable = &schema.Table{
		Name:       "auth",
		Columns:    AuthColumns,
		PrimaryKey: []*schema.Column{AuthColumns[0]},
	}
	// AuthTokenColumns holds the columns for the "auth_token" table.
	AuthTokenColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "client_id", Type: field.TypeString, Default: ""},
		{Name: "access_token", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "expires_in", Type: field.TypeTime, Nullable: true},
	}
	// AuthTokenTable holds the schema information for the "auth_token" table.
	AuthTokenTable = &schema.Table{
		Name:       "auth_token",
		Columns:    AuthTokenColumns,
		PrimaryKey: []*schema.Column{AuthTokenColumns[0]},
	}
	// LinkColumns holds the columns for the "link" table.
	LinkColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "room_name", Type: field.TypeString, Default: ""},
		{Name: "link", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "chat_api", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "chat_api_key", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "token", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "webhook", Type: field.TypeJSON, Nullable: true},
		{Name: "prompt", Type: field.TypeJSON, Nullable: true},
	}
	// LinkTable holds the schema information for the "link" table.
	LinkTable = &schema.Table{
		Name:       "link",
		Columns:    LinkColumns,
		PrimaryKey: []*schema.Column{LinkColumns[0]},
	}
	// RoomColumns holds the columns for the "room" table.
	RoomColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "sid", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeUint8, Default: 0},
		{Name: "start_time", Type: field.TypeTime, Nullable: true},
		{Name: "left_time", Type: field.TypeTime, Nullable: true},
		{Name: "end_time", Type: field.TypeTime, Nullable: true},
		{Name: "vod_status", Type: field.TypeUint8, Nullable: true, Default: 0},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
	}
	// RoomTable holds the schema information for the "room" table.
	RoomTable = &schema.Table{
		Name:       "room",
		Columns:    RoomColumns,
		PrimaryKey: []*schema.Column{RoomColumns[0]},
	}
	// RoomMessageColumns holds the columns for the "room_message" table.
	RoomMessageColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "sid", Type: field.TypeString, Default: ""},
		{Name: "participant_sid", Type: field.TypeString, Default: ""},
		{Name: "participant_name", Type: field.TypeString, Default: ""},
		{Name: "type", Type: field.TypeUint32, Nullable: true, Default: 0},
		{Name: "is_reply", Type: field.TypeUint32, Default: 0},
		{Name: "reply_id", Type: field.TypeUint64, Nullable: true, Default: 0},
		{Name: "event_time", Type: field.TypeTime, Nullable: true},
		{Name: "text", Type: field.TypeString, Default: ""},
	}
	// RoomMessageTable holds the schema information for the "room_message" table.
	RoomMessageTable = &schema.Table{
		Name:       "room_message",
		Columns:    RoomMessageColumns,
		PrimaryKey: []*schema.Column{RoomMessageColumns[0]},
	}
	// RoomVodColumns holds the columns for the "room_vod" table.
	RoomVodColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "sid", Type: field.TypeString, Default: ""},
		{Name: "egress_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 0},
		{Name: "platform", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "vod_type", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "vod_path", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "vod_url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "start_time", Type: field.TypeTime, Nullable: true},
		{Name: "complete_time", Type: field.TypeTime, Nullable: true},
		{Name: "duration", Type: field.TypeUint64, Nullable: true, Default: 0},
	}
	// RoomVodTable holds the schema information for the "room_vod" table.
	RoomVodTable = &schema.Table{
		Name:       "room_vod",
		Columns:    RoomVodColumns,
		PrimaryKey: []*schema.Column{RoomVodColumns[0]},
	}
	// RoomWebhookColumns holds the columns for the "room_webhook" table.
	RoomWebhookColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "sid", Type: field.TypeString, Default: ""},
		{Name: "event", Type: field.TypeString, Default: ""},
		{Name: "event_time", Type: field.TypeTime, Nullable: true},
		{Name: "room", Type: field.TypeJSON, Nullable: true},
		{Name: "participant", Type: field.TypeJSON, Nullable: true},
		{Name: "track", Type: field.TypeJSON, Nullable: true},
		{Name: "egress_info", Type: field.TypeJSON, Nullable: true},
		{Name: "ingress_info", Type: field.TypeJSON, Nullable: true},
	}
	// RoomWebhookTable holds the schema information for the "room_webhook" table.
	RoomWebhookTable = &schema.Table{
		Name:       "room_webhook",
		Columns:    RoomWebhookColumns,
		PrimaryKey: []*schema.Column{RoomWebhookColumns[0]},
	}
	// ServiceWebhookLogColumns holds the columns for the "service_webhook_log" table.
	ServiceWebhookLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "sid", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString, Default: ""},
		{Name: "status_code", Type: field.TypeUint16, Nullable: true, Default: 0},
		{Name: "times", Type: field.TypeUint8, Nullable: true, Default: 0},
		{Name: "request", Type: field.TypeJSON, Nullable: true},
		{Name: "resp", Type: field.TypeJSON, Nullable: true},
	}
	// ServiceWebhookLogTable holds the schema information for the "service_webhook_log" table.
	ServiceWebhookLogTable = &schema.Table{
		Name:       "service_webhook_log",
		Columns:    ServiceWebhookLogColumns,
		PrimaryKey: []*schema.Column{ServiceWebhookLogColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthTable,
		AuthTokenTable,
		LinkTable,
		RoomTable,
		RoomMessageTable,
		RoomVodTable,
		RoomWebhookTable,
		ServiceWebhookLogTable,
	}
)

func init() {
	AuthTable.Annotation = &entsql.Annotation{
		Table: "auth",
	}
	AuthTokenTable.Annotation = &entsql.Annotation{
		Table: "auth_token",
	}
	LinkTable.Annotation = &entsql.Annotation{
		Table: "link",
	}
	RoomTable.Annotation = &entsql.Annotation{
		Table: "room",
	}
	RoomMessageTable.Annotation = &entsql.Annotation{
		Table: "room_message",
	}
	RoomVodTable.Annotation = &entsql.Annotation{
		Table: "room_vod",
	}
	RoomWebhookTable.Annotation = &entsql.Annotation{
		Table: "room_webhook",
	}
	ServiceWebhookLogTable.Annotation = &entsql.Annotation{
		Table: "service_webhook_log",
	}
}
